version: "3"



services:
  # backend:
  #   build: .
  #   ports:
  #     - "8000:8000"

  postgres:
    image: postgres:16.0-alpine
    env_file: .env
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - ./db-vol:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    expose:
      - ${DATABASE_PORT}

  pgadmin:
    image: dpage/pgadmin4:latest
    env_file: .env
    ports:
      - ${PGADMIN_PORT}:80
      - ${PGADMIN_PORT_TLS}:443
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}

volumes:
  boilerplate-db: