/// Flutter icons AppIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcons
///      fonts:
///       - asset: fonts/AppIcons.ttf
///
/// 
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
///
// ignore_for_file: dangling_library_doc_comments, constant_identifier_names

import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcons';
  static const String? _kFontPkg = null;

  static const IconData lungs_virus = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xf004, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xf00c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData times = IconData(0xf00d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock = IconData(0xf017, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book = IconData(0xf02d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark = IconData(0xf02e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData users = IconData(0xf0c0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lightbulb = IconData(0xf0eb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_md = IconData(0xf0f0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stethoscope = IconData(0xf0f1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xf133, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file = IconData(0xf15b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pen = IconData(0xf304, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData briefcase_medical = IconData(0xf469, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData capsules = IconData(0xf46b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dna = IconData(0xf471, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pills = IconData(0xf484, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData prescription_bottle = IconData(0xf485, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData syringe = IconData(0xf48e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tablets = IconData(0xf490, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vial = IconData(0xf492, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hands_helping = IconData(0xf4c4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_bar = IconData(0xf526, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apple_alt = IconData(0xf5d1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bone = IconData(0xf5d7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brain = IconData(0xf5dc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lungs = IconData(0xf604, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData microscope = IconData(0xf610, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone_alt = IconData(0xf879, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
